[package]
name = "kth"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Command line tool for filtering stdin lines that just work"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
